### ISSUE TITLE
Add support for fsproj files

### ISSUE THREAD

**Issue by derwasp** [jmrog/vscode-nuget-package-manager#14]
Even though paket is a standard for f# project, nuget can also be used

**Comment by jmrog** [comment]
Good idea. I've never used fsproj files before, but my understanding is that their format is the same as csproj files. Is that correct?

**Comment by derwasp** [comment]
@jmrog yes, it's the same msbuild format.
You can check it out `dotnet new` with `-lang f#` flag.
e.g.
`dotnet new xunit -lang f#`

**Comment by derwasp** [comment]
Great, thank you!

**Comment by jmrog** [comment]
No problem! I just released it but then rolled it back real quickly, as I spotted an unrelated bug. I'll be releasing a version with the fix in just a minute.

**Comment by jmrog** [comment]
All right, released with fix now. It should work with .fsproj files in the same way as it does with .csproj files! Thanks!
