### ISSUE TITLE
"Could not read project.json, please try again." when adding nuget package to csproj

### ISSUE THREAD

**Issue by innesm** [jmrog/vscode-nuget-package-manager#20]
When trying to add a nuget package to a csproj project (no project.json), I get this error. Should a project.json file be required if the project file is a .csproj?

**Comment by jmrog** [comment]
Can you post a screenshot of the error you're seeing? As far as I know, that string doesn't exist anywhere in this repository, so I'm not sure how you're seeing it. Are you sure you're actually using my extension? There is another, older extension in the extension marketplace that does some similar stuff for project.json projects, here: https://marketplace.visualstudio.com/items?itemName=ksubedi.net-core-project-manager

**Comment by innesm** [comment]
That must be it - how embarrassing. I installed it a while ago as the recommended nuget extension. Sorry to waste your time!

**Comment by jmrog** [comment]
@innesm Not a problem, it happens!
