### ISSUE TITLE
Investigate Issues with Self-Signed Certificates and Transparent Proxies

### ISSUE THREAD

**Issue by jmrog** [jmrog/vscode-nuget-package-manager#24]
See especially [this comment](https://github.com/jmrog/vscode-nuget-package-manager/issues/21#issuecomment-304140628). It may be that this plugin should set the `rejectUnauthorized` TLS option to false when a user has set `http.proxyStrictSSL` to false.

**Comment by ryanmendoza** [comment]
It looks like this was supposed to be fixed in 1.1.4, however I am still seeing the issue.

`Error: request to https://api-v2v3search-0.nuget.org/autocomplete?q=identityserver&prerelease=true&take=100 failed, reason: unable to get local issuer certificate`

http.proxyStrictSSL is set to false in my configuration and is honored by other plugins.

**Comment by jmrog** [comment]
@ryanmendoza v1.1.4 included a "partial" fix for related issues. However, there was additional work I wanted to try out, mentioned in [this comment](https://github.com/jmrog/vscode-nuget-package-manager/issues/21#issuecomment-304140628). I never did get around to doing that, though, because the reporter of #21 resolved his issues and moved on. I'll see what I can do, but may want you to test an early release if that's possible.

**Comment by jmrog** [comment]
@ryanmendoza I implemented the thing that I wanted to implement in the earlier comment I mentioned (at least, as far as I could remember what I wanted to do), and created a new distributable package that is available here: https://github.com/jmrog/vscode-nuget-package-manager/blob/master/dist/vscode-nuget-package-manager-1.1.6.vsix. Would you mind installing that version of the package and seeing whether it resolves your issue? If it does, I'll release as usual through the extension marketplace. If it doesn't, I'll reopen this issue. Thanks!

**Comment by jmrog** [comment]
I'm going to go ahead and release the latest package via the extension marketplace soon, likely some time today.

**Comment by itjstagame** [comment]
@jmrog I'm not sure why no one else has ran in to this issue until now, but it appears this fix will not work for me.

Looking a the code it seems the proxyStrictSSL setting is fully ignored if proxy is blank.
https://github.com/jmrog/vscode-nuget-package-manager/blob/18b028ac7db869f44d877adbe240c5740747986b/src/utils/getFetchOptions.ts#L22

I'm having an issue similar to what bleggett described here https://github.com/Microsoft/vscode/issues/155#issuecomment-170143500
I do not know or need to know my corporate proxy.  For node, etc, I can set just strict-ssl to false and it all works.  I do not supply a proxy.
