### ISSUE TITLE
Is this supposed to work for all Nuget packages?

### ISSUE THREAD

**Issue by Seefer** [jmrog/vscode-nuget-package-manager#27]
Trying to add **Microsoft.EntityFrameworkCore.SqlServer** and **Microsoft.EntityFrameworkCore.Tools** and this plugin seems unable to list them. Should these packages be discoverable by this extension?

**Comment by jmrog** [comment]
Currently, the extension should allow you to locate and package discoverable on nuget.org (eventually, it will also allow you to specify your own package sources -- that's in progress, and is tracked in issue #23). 

I verified that it does in fact discover both of the packages you mentioned. Here's an example for *Microsoft.EntityFrameworkCore.SqlServer*:

![image](https://user-images.githubusercontent.com/8409748/27771689-efeddb46-5f21-11e7-9b8f-5653ecee6ca4.png)

How are you searching for these packages? Maybe it has to do with the search terms you're using? Or maybe you're getting so many results that you're just missing the ones you mentioned?

**Comment by jmrog** [comment]
I'm marking this as closed, given the above. Please re-open if the issue arises again. Thanks!
