### ISSUE TITLE
Reformatted file conflicts with Visual Studio

### ISSUE THREAD

**Issue by wparad** [jmrog/vscode-nuget-package-manager#29]
It seems that at least Visual Studio will automatically remove the line:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` added to the top of the file.

This is a problem for teams working crossplatform, it would it a great improvement to stick to the csproj standard.  [This is the best reference](https://msdn.microsoft.com/en-us/library/dd576348.aspx) that I've found.  Along with [some other](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) sparse documentation.

**Comment by jmrog** [comment]
Thanks for this report. As it's a bug of sorts, rather than a feature request, I'll try to get to it ASAP.

**Comment by wparad** [comment]
For clarification, it seems that there are some changes to line ending too, not sure if that is an OS thing, or a library thing.  Let me know if you are interested in any more details here.

**Comment by jmrog** [comment]
The latest commit/release should resolve issues related to adding and/or removing the XML declaration line (`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`) from files. I haven't had time yet to consider issues related to line endings, so I'll open that as a separate issue.
