### ISSUE TITLE
At least one <Package Reference> tag

### ISSUE THREAD

**Issue by CarlosAzocar** [jmrog/vscode-nuget-package-manager#5]
It seems that if there is not at least one **<PackageReference></ PackageReference>** tag does not install the package.

![2017-03-11 3](https://cloud.githubusercontent.com/assets/18235355/23826171/01a8f766-066d-11e7-82ce-b98265cf640a.png)
![2017-03-11 4](https://cloud.githubusercontent.com/assets/18235355/23826170/00f9a1a8-066d-11e7-98a2-045f25a3b217.png)

**Comment by jmrog** [comment]
Good catch! I'll fix this issue shortly. Thanks!

**Comment by jmrog** [comment]
This issue should be fixed once I merge d551d43 into master and release. I just want to write tests first.

**Comment by jmrog** [comment]
Should be all set. Let me know if the issue persists (or you find new ones)!
