### ISSUE TITLE
Fialed to install a package

### ISSUE THREAD

**Issue by akontsevich** [jmrog/vscode-nuget-package-manager#6]
Was unable to install `Microsoft.AspNetCore.Server.Kestrel` package via Your vscode-nuget-package-manager - it did not find it, forced to use terminal:
`# dotnet add package Microsoft.AspNetCore.Server.Kestrel `
which works successfully.

**Comment by jmrog** [comment]
@akontsevich Thanks for the report. Do you know whether there are specific steps I can take to reproduce this issue? I just tried to install `Microsoft.AspNetCore.Server.Kestrel` using the plugin on my own machine and it worked fine. (Did you already have some dependencies installed? There is currently an open issue (#5) where the plugin fails to install if you don't have any package references in your `.csproj` file when you try to use it.)

**Comment by jmrog** [comment]
Here is an example of it working fine for me:

![working example](https://media.giphy.com/media/l0Iyg7b8FguEU4ojC/giphy.gif)

**Comment by akontsevich** [comment]
Yes, works this way for me too, thanks. Thought auto-complete show me while typing.

**Comment by jmrog** [comment]
Ah, gotcha. Yeah, that would be very nice, but it unfortunately isn't possible, as far as I know, given the way that VS Code extensions work (the search box API only provides data once the user actually hits Enter (or cancels)).
